const dataCliente = {
  primer_nombre: "Pablo",
  segundo_nombre: "Adrian",
  primer_apellido: "Gonzalez",
  segundo_apellido: "Salazar",
  tipo_doc: "Cedula Ciudadanía",
  num_doc: "9873241",
  movil: "3207809668",
  placa: "PEREIRA",
  email: "etereosum@gmail.com",
  fecha_exp: "2000-01-01",
  lugar_exp: "PEREIRa",
  fecha_nacimiento: "1982-01-25",
  lugar_nacimiento: "PEREIRA",
  genero: "Masculino",
  estado_civil: "Soltero/a",
  nivel_estudios: "Universitario",
  estrato: "2",
  fijo: "3202154",
  municipio_id: "834",
  barrio: "Camilo Mejia Duque",
  direccion: "Manzana 8 Casa 13",
  anos_residencia: "",
  meses_residencia: 30,
  tipo_vivienda: "Familiar",
  ocupacion: "Ingeniero",
  doc_empresa: "",
  tipo_actividad: "Independiente",
  empresa: "etereosum",
  dir_empresa: "manzana 8 casa 13 Camilo Mejia Duque Frailes Dosquebradas",
  tel_empresa: "3207809668",
  fecha_vinculacion: "2022-01-01",
  descripcion_actividad: "Desarrollo de software",
  cargo: "Desarrollador web",
  tipo_contrato: "Indefinido",
  password: "123456",
  confirm: "123456"
};

module.exports = dataCliente;
